######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 11 11:28:23 2015
######################################################################

MOC_DIR = .moc
OBJECTS_DIR = .obj

QT += phonon

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mywidget.h
SOURCES += main.cpp mywidget.cpp
