#############################################################################
# Makefile for building: batty
# Generated by qmake (2.01a) (Qt 4.6.3) on: ?? ????. 18 13:46:03 2015
# Project:  batty.pro
# Template: app
# Command: /usr/lib/qt46/bin/qmake -unix -o Makefile batty.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_PHONON_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/lib/qt46/mkspecs/linux-g++ -I. -I/usr/lib/qt46/include/QtCore -I/usr/lib/qt46/include/QtGui -I/usr/lib/qt46/include/phonon -I/usr/lib/qt46/include -I. -I/usr/lib/qt46/include/phonon_compat -I.moc
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/qt46/lib -lphonon -L/usr/lib/qt46/lib -lQtDBus -lQtXml -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/qt46/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = 
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = .obj/

####### Files

SOURCES       = main.cpp \
		mywidget.cpp .moc/moc_mywidget.cpp
OBJECTS       = .obj/main.o \
		.obj/mywidget.o \
		.obj/moc_mywidget.o
DIST          = /usr/lib/qt46/mkspecs/common/g++.conf \
		/usr/lib/qt46/mkspecs/common/unix.conf \
		/usr/lib/qt46/mkspecs/common/linux.conf \
		/usr/lib/qt46/mkspecs/qconfig.pri \
		/usr/lib/qt46/mkspecs/features/qt_functions.prf \
		/usr/lib/qt46/mkspecs/features/qt_config.prf \
		/usr/lib/qt46/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt46/mkspecs/features/default_pre.prf \
		/usr/lib/qt46/mkspecs/features/release.prf \
		/usr/lib/qt46/mkspecs/features/default_post.prf \
		/usr/lib/qt46/mkspecs/features/warn_on.prf \
		/usr/lib/qt46/mkspecs/features/qt.prf \
		/usr/lib/qt46/mkspecs/features/unix/thread.prf \
		/usr/lib/qt46/mkspecs/features/moc.prf \
		/usr/lib/qt46/mkspecs/features/resources.prf \
		/usr/lib/qt46/mkspecs/features/uic.prf \
		/usr/lib/qt46/mkspecs/features/yacc.prf \
		/usr/lib/qt46/mkspecs/features/lex.prf \
		/usr/lib/qt46/mkspecs/features/include_source_dir.prf \
		batty.pro
QMAKE_TARGET  = batty
DESTDIR       = 
TARGET        = batty

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: batty.pro  /usr/lib/qt46/mkspecs/linux-g++/qmake.conf /usr/lib/qt46/mkspecs/common/g++.conf \
		/usr/lib/qt46/mkspecs/common/unix.conf \
		/usr/lib/qt46/mkspecs/common/linux.conf \
		/usr/lib/qt46/mkspecs/qconfig.pri \
		/usr/lib/qt46/mkspecs/features/qt_functions.prf \
		/usr/lib/qt46/mkspecs/features/qt_config.prf \
		/usr/lib/qt46/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt46/mkspecs/features/default_pre.prf \
		/usr/lib/qt46/mkspecs/features/release.prf \
		/usr/lib/qt46/mkspecs/features/default_post.prf \
		/usr/lib/qt46/mkspecs/features/warn_on.prf \
		/usr/lib/qt46/mkspecs/features/qt.prf \
		/usr/lib/qt46/mkspecs/features/unix/thread.prf \
		/usr/lib/qt46/mkspecs/features/moc.prf \
		/usr/lib/qt46/mkspecs/features/resources.prf \
		/usr/lib/qt46/mkspecs/features/uic.prf \
		/usr/lib/qt46/mkspecs/features/yacc.prf \
		/usr/lib/qt46/mkspecs/features/lex.prf \
		/usr/lib/qt46/mkspecs/features/include_source_dir.prf \
		/usr/lib/qt46/lib/libphonon.prl \
		/usr/lib/qt46/lib/libQtDBus.prl \
		/usr/lib/qt46/lib/libQtXml.prl \
		/usr/lib/qt46/lib/libQtCore.prl \
		/usr/lib/qt46/lib/libQtGui.prl
	$(QMAKE) -unix -o Makefile batty.pro
/usr/lib/qt46/mkspecs/common/g++.conf:
/usr/lib/qt46/mkspecs/common/unix.conf:
/usr/lib/qt46/mkspecs/common/linux.conf:
/usr/lib/qt46/mkspecs/qconfig.pri:
/usr/lib/qt46/mkspecs/features/qt_functions.prf:
/usr/lib/qt46/mkspecs/features/qt_config.prf:
/usr/lib/qt46/mkspecs/features/exclusive_builds.prf:
/usr/lib/qt46/mkspecs/features/default_pre.prf:
/usr/lib/qt46/mkspecs/features/release.prf:
/usr/lib/qt46/mkspecs/features/default_post.prf:
/usr/lib/qt46/mkspecs/features/warn_on.prf:
/usr/lib/qt46/mkspecs/features/qt.prf:
/usr/lib/qt46/mkspecs/features/unix/thread.prf:
/usr/lib/qt46/mkspecs/features/moc.prf:
/usr/lib/qt46/mkspecs/features/resources.prf:
/usr/lib/qt46/mkspecs/features/uic.prf:
/usr/lib/qt46/mkspecs/features/yacc.prf:
/usr/lib/qt46/mkspecs/features/lex.prf:
/usr/lib/qt46/mkspecs/features/include_source_dir.prf:
/usr/lib/qt46/lib/libphonon.prl:
/usr/lib/qt46/lib/libQtDBus.prl:
/usr/lib/qt46/lib/libQtXml.prl:
/usr/lib/qt46/lib/libQtCore.prl:
/usr/lib/qt46/lib/libQtGui.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile batty.pro

dist: 
	@$(CHK_DIR_EXISTS) .obj/batty1.0.0 || $(MKDIR) .obj/batty1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .obj/batty1.0.0/ && $(COPY_FILE) --parents mywidget.h .obj/batty1.0.0/ && $(COPY_FILE) --parents main.cpp mywidget.cpp .obj/batty1.0.0/ && (cd `dirname .obj/batty1.0.0` && $(TAR) batty1.0.0.tar batty1.0.0 && $(COMPRESS) batty1.0.0.tar) && $(MOVE) `dirname .obj/batty1.0.0`/batty1.0.0.tar.gz . && $(DEL_FILE) -r .obj/batty1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: .moc/moc_mywidget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) .moc/moc_mywidget.cpp
.moc/moc_mywidget.cpp: mywidget.h
	/usr/lib/qt46/bin/moc $(DEFINES) $(INCPATH) mywidget.h -o .moc/moc_mywidget.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

.obj/main.o: main.cpp mywidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/main.o main.cpp

.obj/mywidget.o: mywidget.cpp mywidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/mywidget.o mywidget.cpp

.obj/moc_mywidget.o: .moc/moc_mywidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_mywidget.o .moc/moc_mywidget.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

